/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PlanifierRencontreRouteImport } from './routes/planifier-rencontre'
import { Route as EngagementsRouteImport } from './routes/engagements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EngagementsStandardsRouteImport } from './routes/engagements.standards'
import { Route as DebugSsrRouteImport } from './routes/debug.ssr'
import { Route as ApiCalendarEventRouteImport } from './routes/api/calendar-event'
import { Route as AideGithubRouteImport } from './routes/aide.github'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanifierRencontreRoute = PlanifierRencontreRouteImport.update({
  id: '/planifier-rencontre',
  path: '/planifier-rencontre',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsRoute = EngagementsRouteImport.update({
  id: '/engagements',
  path: '/engagements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementsStandardsRoute = EngagementsStandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => EngagementsRoute,
} as any)
const DebugSsrRoute = DebugSsrRouteImport.update({
  id: '/debug/ssr',
  path: '/debug/ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarEventRoute = ApiCalendarEventRouteImport.update({
  id: '/api/calendar-event',
  path: '/api/calendar-event',
  getParentRoute: () => rootRouteImport,
} as any)
const AideGithubRoute = AideGithubRouteImport.update({
  id: '/aide/github',
  path: '/aide/github',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/engagements': typeof EngagementsRouteWithChildren
  '/planifier-rencontre': typeof PlanifierRencontreRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/aide/github': typeof AideGithubRoute
  '/api/calendar-event': typeof ApiCalendarEventRoute
  '/debug/ssr': typeof DebugSsrRoute
  '/engagements/standards': typeof EngagementsStandardsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/engagements': typeof EngagementsRouteWithChildren
  '/planifier-rencontre': typeof PlanifierRencontreRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/aide/github': typeof AideGithubRoute
  '/api/calendar-event': typeof ApiCalendarEventRoute
  '/debug/ssr': typeof DebugSsrRoute
  '/engagements/standards': typeof EngagementsStandardsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/engagements': typeof EngagementsRouteWithChildren
  '/planifier-rencontre': typeof PlanifierRencontreRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/aide/github': typeof AideGithubRoute
  '/api/calendar-event': typeof ApiCalendarEventRoute
  '/debug/ssr': typeof DebugSsrRoute
  '/engagements/standards': typeof EngagementsStandardsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/engagements'
    | '/planifier-rencontre'
    | '/services'
    | '/admin/login'
    | '/aide/github'
    | '/api/calendar-event'
    | '/debug/ssr'
    | '/engagements/standards'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/engagements'
    | '/planifier-rencontre'
    | '/services'
    | '/admin/login'
    | '/aide/github'
    | '/api/calendar-event'
    | '/debug/ssr'
    | '/engagements/standards'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/engagements'
    | '/planifier-rencontre'
    | '/services'
    | '/admin/login'
    | '/aide/github'
    | '/api/calendar-event'
    | '/debug/ssr'
    | '/engagements/standards'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  EngagementsRoute: typeof EngagementsRouteWithChildren
  PlanifierRencontreRoute: typeof PlanifierRencontreRoute
  ServicesRoute: typeof ServicesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AideGithubRoute: typeof AideGithubRoute
  ApiCalendarEventRoute: typeof ApiCalendarEventRoute
  DebugSsrRoute: typeof DebugSsrRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planifier-rencontre': {
      id: '/planifier-rencontre'
      path: '/planifier-rencontre'
      fullPath: '/planifier-rencontre'
      preLoaderRoute: typeof PlanifierRencontreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements': {
      id: '/engagements'
      path: '/engagements'
      fullPath: '/engagements'
      preLoaderRoute: typeof EngagementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagements/standards': {
      id: '/engagements/standards'
      path: '/standards'
      fullPath: '/engagements/standards'
      preLoaderRoute: typeof EngagementsStandardsRouteImport
      parentRoute: typeof EngagementsRoute
    }
    '/debug/ssr': {
      id: '/debug/ssr'
      path: '/debug/ssr'
      fullPath: '/debug/ssr'
      preLoaderRoute: typeof DebugSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar-event': {
      id: '/api/calendar-event'
      path: '/api/calendar-event'
      fullPath: '/api/calendar-event'
      preLoaderRoute: typeof ApiCalendarEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/github': {
      id: '/aide/github'
      path: '/aide/github'
      fullPath: '/aide/github'
      preLoaderRoute: typeof AideGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EngagementsRouteChildren {
  EngagementsStandardsRoute: typeof EngagementsStandardsRoute
}

const EngagementsRouteChildren: EngagementsRouteChildren = {
  EngagementsStandardsRoute: EngagementsStandardsRoute,
}

const EngagementsRouteWithChildren = EngagementsRoute._addFileChildren(
  EngagementsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  EngagementsRoute: EngagementsRouteWithChildren,
  PlanifierRencontreRoute: PlanifierRencontreRoute,
  ServicesRoute: ServicesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AideGithubRoute: AideGithubRoute,
  ApiCalendarEventRoute: ApiCalendarEventRoute,
  DebugSsrRoute: DebugSsrRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
